name: 'Prepare Package'
description: 'Sets the content of the package and build it.'
inputs:
  overwrite-publish-config:
    description: 'Changes the publish config registry URL.'
    required: false
runs:
  using: "composite"
  steps:
    - name: Set Name of the Package
      run: ${GITHUB_ACTION_PATH}/set-publish-config.sh ${{ inputs.overwrite-publish-config }} "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
      shell: bash

    - name: Upload Artifact
      run: ${GITHUB_ACTION_PATH}/prepare-package-contents.sh
      shell: bash

    - run: npm pack
      shell: bash