on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact for this package.'
        required: false
        type: string
        default: package
      overwrite-publish-config:
        description: 'Changes the publish config registry URL.'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.output.outputs.artifact-path }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download JSON
        uses: actions/download-artifact@v3
        with:
          name: package-json

      - name: Download Changelog
        uses: actions/download-artifact@v3
        with:
          name: changelog

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build Source Generator
        run: (cd SourceGenerator~ && dotnet build --configuration Release)
        shell: bash

      - name: Modify Registry Settings
        run: ./.github/set-publish-config.sh ${{ inputs.overwrite-publish-config }} "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
        shell: bash

      - name: Prepare Package Contents
        run: ./.github/prepare-package-contents.sh
        shell: bash

      - name: Pack
        run: npm pack
        shell: bash

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: "*.tgz"
          retention-days: 30