on:
  workflow_call:
    inputs:
      package-name:
        description: 'Change the name of the package.'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: javier-games/semantic-version-common-dependencies@v1.1

      - name: Set Version
        run: semantic-release
        shell: bash

      - name: Pack
        uses: ./.github/actions/prepare-package
        with:
          name: ${{ inputs.package-name }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: "*.tgz"