on:
  workflow_call:
    inputs:
      registry-url:
        description: 'URL of the target registry to deploy.'
        required: false
        type: string
        default: 'https://npm.pkg.github.com'
      public:
        description: "Whether to publish publicly or restricted"
        required: false
        type: boolean
        default: false
    secrets:
      access-token:
        description: "Token required for publishing."
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: ${{ inputs.registry-url }}

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Publish
        run: |
          if ${{ inputs.public }}; then
            npm publish *.tgz --access public
          else
            npm publish *.tgz --access restricted
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.access-token }}