on:
  push:
    branches:
      - main
      - release/*
      - hotfix/*

jobs:

  build:
    name: Build Package
    uses: ./.github/workflows/build-package-workflow.yml

  deploy-public:
    name: Deploy Package
    needs: build
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-package-workflow.yml
    with:
      registry-url: 'https://registry.npmjs.org'
      public: true
    secrets:
      access-token: ${{ secrets.NPM_TOKEN }}