on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - release/*
      - hotfix/*
      - develop

jobs:

  set-version:
    name: Set Version
    uses: ./.github/workflows/semantic-version-workflow.yml
    with:
      dry: true

  build-github:
    name: Build Package for GitHub Registry
    needs: set-version
    uses: ./.github/workflows/build-package-workflow.yml
    with:
      overwrite-publish-config: "https://npm.pkg.github.com/@$GITHUB_REPOSITORY_OWNER"
      artifact-name: github-npm-package

  build-npm:
    name: Build Package for NPM Registry
    needs: set-version
    uses: ./.github/workflows/build-package-workflow.yml