on:
  workflow_call:
    inputs:
      dry:
        description: "Whether to publish publicly or restricted"
        required: false
        type: boolean
        default: false
    outputs:
      version:
        description: "Semantic version detected."
        value: ${{ jobs.set-version.outputs.version }}

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.output.outputs.version }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: javier-games/semantic-version-common-dependencies@v1.1

      - name: Get Current Version
        run: jq -r .version package.json > .version

      - name: Set Version
        run: |
          if ${{ inputs.dry }}; then
            semantic-release --dry-run
          else
            semantic-release
          fi

      - name: Output Version
        id: output
        run: echo "version=$(cat .version)" >> $GITHUB_OUTPUT

      - name: Upload Modified package.json
        uses: actions/upload-artifact@v3
        with:
          name: package-json
          path: "package.json"
          retention-days: 1

      - name: Upload Modified CHANGELOG.md
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: "CHANGELOG.md"
          retention-days: 1